services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/webroot
      - ./certbot-logs:/var/log/letsencrypt
    entrypoint: >
      /bin/sh -c '
      if [ ! -d "/etc/letsencrypt/live/langkilde.se" ]; then 
        certbot certonly --webroot --webroot-path=/webroot -d langkilde.se -d www.langkilde.se -d daniel.langkilde.se -d www.daniel.langkilde.se;
      fi;
      while :; do 
        certbot renew --quiet;
        sleep 12h;
      done'
    networks:
      - webnet
    depends_on:
      - nginx

  langkilde-se:
    build: .
    container_name: langkilde-se
    volumes:
      - ./posts:/app/posts
    restart: always
    networks:
      - webnet
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./certs:/etc/letsencrypt:ro
      - ./webroot:/webroot
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - langkilde-se
    networks:
      - webnet

networks:
  webnet: