version: "3.8"

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/webroot
      - ./certbot-logs:/var/log/letsencrypt
    entrypoint: >
      /bin/sh -c '
      if [ ! -d "/etc/letsencrypt/live/langkilde.se" ]; then 
        certbot certonly --webroot --webroot-path=/webroot -d langkilde.se -d www.langkilde.se -d daniel.langkilde.se -d www.daniel.langkilde.se;
      fi;
      while :; do 
        certbot renew --quiet;
        sleep 12h;
      done'
    networks:
      - shared_network
    depends_on:
      - nginx

  langkilde-se:
    build: .
    container_name: langkilde-se
    volumes:
      - ./posts:/app/posts
    restart: always
    networks:
      - shared_network
    expose:
      - 8000

networks:
  shared_network:
    external: true