services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./webroot:/webroot
      - ./certbot-logs:/var/log/letsencrypt
    entrypoint: >
      /bin/sh -c '
      trap exit TERM; 
      if [ ! -d "/etc/letsencrypt/live" ]; then 
        certbot certonly --webroot --webroot-path=/webroot -d langkilde.se -d www.langkilde.se;
      fi;
      while :; do 
        certbot renew; 
        sleep 12h & wait $${!}; 
      done;'

    command: [ "certonly", "--webroot", "--webroot-path=/webroot", "-d", "langkilde.se", "-d", "www.langkilde.se" ]
    networks:
      - webnet
    depends_on:
      - nginx

  langkilde-se:
    build: .
    container_name: langkilde-se
    restart: always
    networks:
      - webnet
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./certs/live/langkilde.se/fullchain.pem:/etc/ssl/certs/nginx.crt
      - ./certs/live/langkilde.se/privkey.pem:/etc/ssl/private/nginx.key
      - ./webroot:/webroot
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - langkilde-se
    networks:
      - webnet

networks:
  webnet: