services:
  astro:
    build: .
    container_name: astro
    volumes:
      - ./build:/app/dist  # Share Astro build output
    restart: always
    networks:
      - shared_network
    ports:
      - "8000:8080"  # maps container port 8080 to host port 8000

networks:
  shared_network:
    external: true