services:
  astro:
    build: .
    container_name: astro
    volumes:
      - ./dist:/srv/astro  # Map built files to where nginx expects them
    restart: "no"  # Don't restart - this just builds and exits
    networks:
      - shared_network

networks:
  shared_network:
    external: true