version: "3.8"

services:
  langkilde-se:
    build: .
    container_name: langkilde-se
    volumes:
      - ./posts:/app/posts
    restart: always
    networks:
      - shared_network
    expose:
      - 8000

networks:
  shared_network:
    external: true